//
// Created by Eric Zhao on 12/4/2022.
//

#ifndef INTERNETPROJECT_INCLUDE_CONSTANT_H_
#define INTERNETPROJECT_INCLUDE_CONSTANT_H_

#define BUF_SIZE 1024*1024
#define MAX_CONNECTION_NUMBER 1024
#define ECHO_PORT 9999

#endif //INTERNETPROJECT_INCLUDE_CONSTANT_H_
